### ISSUE TITLE
Task: Create UserPage > UserInfo Panel

### ISSUE THREAD

**Issue by arunbhardwaj** [roman-marxists/marxet#22]
# Task: create the UserInfo panel

### As a user, I should be able to see:
Public info
- [ ] my profile picture
- [ ] my name
- [ ] my location
- [ ] my barter rating
- [ ] my upvotes (maybe as a percentage of users i've traded with? default 100?)
- [ ] bio

### As an authenticated user, I should be able to see

Authenticated info:
- [ ] transaction list (maybe a link to redirect)
- [ ] (?) more specific location info
- [ ] (?) edit button or
- [ ] (?) settings button (perhaps this should be top right of the user page)
- [ ] insert more info here...
