### ISSUE TITLE
Task: User Inventory

### ISSUE THREAD

**Issue by arunbhardwaj** [roman-marxists/marxet#23]
# Task: create a user inventory/listing section

## Description:
As a user I should be able to see my inventory of items. I should be able to scroll through them infinitely in the middle of my page. I should be able to add a new item by clicking a button.  I should be able to click on items in my inventory to look at more pictures of it, or other info I've added upon upload. I should also be able to see the number of views each product has seen, number of people who've added it to their watchlist, and number of trade offers.

- [ ] scroll infinitely
- [ ] create a new listing
- [ ] click on items to view more info
- [ ] views for each item
- [ ] watches for each item
- [ ] # of trade offers for each item
- [ ] (insert more here)
